import {
  BarChart3,
  BookText,
  ConciergeBell,
  Building2,
  CalendarDays,
  Clock,
  FlaskConical,
  Layers,
  LayoutDashboard,
  Pill,
  SlidersHorizontal,
  Receipt,
  ShieldAlert,
  Tablets,
  TestTube,
  Stethoscope,
  Users,
  UserCog,
  UserPlus,
  UserRound,
  type LucideIcon,
} from 'lucide-react'

/** One icon per nav key. Shared by the sidebar and the dashboard so they never drift. */
export const NAV_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  reception: ConciergeBell,
  queue: Clock,
  appointments: CalendarDays,
  patients: UserRound,
  patientNew: UserPlus,
  consultations: Stethoscope,
  icd: BookText,
  interactions: ShieldAlert,
  lab: FlaskConical,
  pharmacy: Pill,
  users: UserCog,
  modules: SlidersHorizontal,
  departments: Building2,
  practitioners: Users,
  services: Receipt,
  labTests: TestTube,
  labPanels: Layers,
  drugs: Tablets,
  reports: BarChart3,
}
